
- name: test if ohmyzsh has been installed before
  stat:
    path: "{{ user_home }}/.oh-my-zsh/oh-my-zsh.sh"
  register: path

# Clone oh-my-zsh if not present
- name: clone oh-my-zsh repo
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ user_home }}/.oh-my-zsh"
    depth: "1"
  when: not path.stat.exists

# Install Powerlevel9k
- name: install powerlevel9k
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ user_home }}/.oh-my-zsh/custom/themes/powerlevel9k"
    depth: "1"
  when: not path.stat.exists

# Install Fonts
- name: create directoriesfor fonts
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ user_home }}/.config/fontconfig/conf.d"
    - "{{ user_home }}/.fonts/"

- name: Download fonts.otf
  git:
    repo: "https://github.com/powerline/fonts.git"
    depth: 1
    dest: "/tmp/fonts"

- name: Install fonts.conf
  shell:
    cmd: "./install.sh"
    chdir: "/tmp/fonts"

- name: Clean font install
  file:
    path: "/tmp/fonts"
    state: "absent"

- name: deploy .zshrc file
  template:
    src: "zshrc.sh"
    dest: "{{ user_home }}/.zshrc"
    owner: "{{ whoami }}"

# Set default shell
- name: set zsh as default shell
  become: true
  shell: chsh -s $(which zsh) {{ whoami }}
  changed_when: false
