- include: homebrew.yaml
  when: ansible_os_family == 'Darwin'
  become: yes
  
- include: apt.yaml
  when: ansible_pkg_mgr == 'apt'
  become: yes

- include: base.yaml
  become: yes

- set_fact:
    role_basic_done: true
