- include: homebrew.yaml
  when: ansible_os_family == 'Darwin'
  sudo: no
  
- include: apt.yaml
  when: ansible_pkg_mgr == 'apt'
  sudo: no

- include: base.yaml
  sudo: no

- set_fact:
    role_basic_done: true
